# Pandas and Baseball
This project focuses on dataframe basics with `pandas`. I am trying to avoid you hardcoding values or modifying the data file, so you each need to specify the path to your data file and the filename:

In [ ]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [ ]:
# load data
file_path = "."  # CHANGE ME!
file_name = "batting_2025.csv"  # CHANGE ME!
file = os.path.join(file_path, file_name)
hitting = pd.read_csv(file)
hitting

,Rk,Player,Age,Team,G,PA,AB,R,H,2B,3B,HR,RBI,OBP,SLG,OPS,Player-additional
0,1,Francisco Lindor#,31,NYM,160,732,644,117,172,35,0,31,86,0.346,0.466,0.811,lindofr01
1,2,Rafael Devers*,28,2TM,163,729,607,99,153,33,0,35,109,0.372,0.479,0.851,deverra01
2,2,Rafael Devers*,28,BOS,73,334,272,47,74,18,0,15,58,0.401,0.504,0.905,deverra01
3,2,Rafael Devers*,28,SFG,90,395,335,52,79,15,0,20,51,0.347,0.460,0.807,deverra01
4,3,Shohei Ohtani*,30,LAD,158,727,611,146,172,25,9,55,102,0.392,0.622,1.014,ohtansh01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,759,Victor Vodnik,25,COL,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,vodnivi01
918,760,Ryan Walker,29,SFG,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,walkery01
919,761,Chad Wallach,33,LAA,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,wallach01
920,762,Garrett Whitlock,29,BOS,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,whitlga01
921,763,Bryse Wilson,27,CHW,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,wilsobr02

When I grade these, I will change `file_path` and `file_name` to the directory where a _new_ dataset is saved on my computer (I will use a different season's statistics).
If you have answered the following question by changing your data file or hardcoding values, your code will not function properly when I load in a new data file.
All prompts should function properly when a new file is read into `hitting`.
As such, you must submit the python or jupyter source when you submit your assignment.

## Removing the summative row for players that were traded
As discussed in class, some players appear multiple times in the dataset.
This occurs for players who were traded between teams during the season.
For a player traded once, he will have three rows: one for each team plus an additional row that aggregates his totals under the team name `2TM`.
For a player traded two times, his totals will be aggregated for the team name `3TM`.

In [ ]:
# investigating data mentioned
two_teamers = hitting[hitting["Team"] == "2TM"].sort_values(by="Player")
print(two_teamers)

      Rk           Player  Age Team    G   PA   AB   R    H  2B  3B  HR  RBI  \
203  172    Adam Frazier*   33  2TM  134  459  419  43  112  20   0   7   44
472  391      Alan Roden*   25  2TM   55  153  136  17   26   6   1   2    9
316  267        Alex Call   30  2TM  110  322  270  43   72  13   2   5   31
734  592      Ali Sánchez   28  2TM   12   23   23   2    5   2   0   0    0
426  357     Amed Rosario   29  2TM   62  191  181  20   50  11   0   6   23
..   ...              ...  ...  ...  ...  ...  ...  ..  ...  ..  ..  ..  ...
574  466    Vidal Bruján#   27  2TM   59   94   86  14   21   5   0   0    8
558  453      Vinny Capra   28  2TM   47  105   96  10   12   2   0   1    6
615  495  Will Robertson*   27  2TM   27   75   70   2    9   1   0   0    9
480  395     Will Wagner*   26  2TM   55  149  129  15   29   7   0   0    7
207  174    Willi Castro#   28  2TM  120  454  402  58   91  17   3  11   33

       OBP    SLG    OPS Player-additional
203  0.319  0.365  0.684         fraziad01
472  0.261  0.294  0.556         rodenal01
316  0.361  0.385  0.746          callal02
734  0.217  0.304  0.522         sanchal04
426  0.309  0.436  0.745         rosaram01
..     ...    ...    ...               ...
574  0.298  0.302  0.600         brujavi01
558  0.157  0.177  0.334         capravi01
615  0.173  0.143  0.316         roberwi02
480  0.324  0.279  0.603         wagnewi01
207  0.313  0.366  0.679         castrwi01

[75 rows x 17 columns]

In [ ]:
# continued investigation
three_teamers = hitting[hitting["Team"] == "3TM"].sort_values(by="Player")
three_teamers.head()

,Rk,Player,Age,Team,G,PA,AB,R,H,2B,3B,HR,RBI,OBP,SLG,OPS,Player-additional
713,577,Buddy Kennedy,26,3TM,13,32,29,2,2,1,0,0,1,0.156,0.103,0.260,kennebu01
581,470,Garrett Hampson,30,3TM,62,91,77,19,11,2,0,0,1,0.250,0.169,0.419,hampsga01
667,537,Travis Jankowski*,34,3TM,25,50,45,8,11,2,0,0,2,0.286,0.289,0.575,jankotr01
573,466,Vidal Bruján#,27,3TM,60,95,87,14,22,5,0,0,8,0.305,0.310,0.616,brujavi01

**PROMPT** Create a variable called `players_traded_once` that contains the players who were traded once. Create a variable called `players_traded_twice` that contains the players who were traded twice.

In [ ]:
# already calculated these above, alias them
players_traded_once = two_teamers
players_traded_twice = three_teamers

**PROMPT** Create a new dataframe that contains only the aggregate totals of the traded players.

In [ ]:
# First, need to take a look at a set of rows describing a single player that's been traded once/twice
# looking at the head() dumps above, let's look at a single player who has been traded twice. Looking at you, Buddy Kennedy...
# hitting[hitting["Player"] == "Buddy Kennedy"]
# hitting[hitting["Player"] == "Garrett Hampson"]
players_traded_once.head()

,Rk,Player,Age,Team,G,PA,AB,R,H,2B,3B,HR,RBI,OBP,SLG,OPS,Player-additional
203,172,Adam Frazier*,33,2TM,134,459,419,43,112,20,0,7,44,0.319,0.365,0.684,fraziad01
472,391,Alan Roden*,25,2TM,55,153,136,17,26,6,1,2,9,0.261,0.294,0.556,rodenal01
316,267,Alex Call,30,2TM,110,322,270,43,72,13,2,5,31,0.361,0.385,0.746,callal02
734,592,Ali Sánchez,28,2TM,12,23,23,2,5,2,0,0,0,0.217,0.304,0.522,sanchal04
426,357,Amed Rosario,29,2TM,62,191,181,20,50,11,0,6,23,0.309,0.436,0.745,rosaram01

**PROMPT** Update the dataframe `hitting` so that the rows for the aggregate totals of the traded players are removed.

In [ ]:
hitting = hitting.drop(hitting[(hitting.Team == "2TM") | (hitting.Team == "3TM")].index)

## Adding a column for batting average
A player's batting average is computed by taking the number of hits divided by the number of at bats,
\begin{equation}
\text{batting average} = \frac{\text{\# Hits}}{\text{\# At Bats}}.
\end{equation}
These statistics for each player are found under the `H` and `AB` columns, respectively.

**PROMPT** Add a column to `hitting` called `avg` that provides the players batting average. For players that played on multiple teams, compute their average while playing for each team (so two different averages for two different teams).

In [ ]:
hitting["avg"] = hitting["H"] / hitting["AB"]
hitting["avg"].head()

# TODO Factor in players traded multiple times, but I literally just removed all those rows as per above??? Wat?

0    0.267081
2    0.272059
3    0.235821
4    0.281506
5    0.272436
Name: avg, dtype: float64

**PROMPT** Find the average batting average of all the MLB player's batting averages by averaging each player's batting average. For traded players, you can treat the rows for separate teams as separate players.

In [ ]:
overall_avg = hitting["avg"].mean()
print(f"The average batting average of all the MLB players is {overall_avg}.")

The average batting average of all the MLB players is 0.21600506365255215.

**PROMPT** Find the average batting average of all the MLB players by taking the _total_ number of hits divided by the _total_ number of at bats.

In [ ]:
total_hits = hitting["H"].sum()
total_at_bats = hitting["AB"].sum()
overall_avg_total = total_hits / total_at_bats
overall_avg, overall_avg_total
print(f"The average batting average of all the MLB players is {overall_avg_total} (done by summing all the hits and dividing by all the attempts).")

(np.float64(0.21600506365255215), np.float64(0.24524635839280476))

**PROMPT** Are the two averages the same? Why or why not?

In [ ]:
overall_avg == overall_avg_total

**ANSWER**
The averages are not equal. For any useful comparison, I'd use the overall_avg as calculated above, by ``hitting["avg"].mean()``, since it treats each player's average equally, rather than aggregating all hits and at-bats across all players, which could be skewed by a few players with very high count for at-bats, etc.

## Home Run Tracking

**Prompt** Create a `Series` whose index is a `MultiIndex` of `{Team, Player}` pairs whose values give the home run totals for the top two players on each team.

In [ ]:
# Expecting a result that looks approximately like this:
# ( 'NYM', 'Francisco Lindor#', 123 ) # where 123 is the home run total for the top two on the NYM team
# how exactly to accomplish this top TWO home run totals per team... without running a sum(top 2 home run players) query for each and every team...

# try to set index on the df in the first place?
# hitting.set_index(["Team", "Player"], inplace=True) # KeyError: "None of ['Team', 'Player'] are in the columns"

# this results in a pandas.core.groupby.generic.DataFrameGroupBy object
hitting_series = hitting.groupby(
    ["Team", "Player"]
)  # this is still a DF groupby object right now, not a Series? But this is the way Kaggle demonstrated it...

hitting.head()

# MI = pd.MultiIndex.from_frame(hitting, names=["Team", "Player"])
# hitting_series.head()
# type(hitting_series)
# hitting_series#[Team == "NYM"][Player == "Francisco Lindor#"]
hitting.loc[(hitting["Team"] == "NYM") & (hitting["Player"] == "Francisco Lindor#")]

**Prompt** Create a `Series` whose index is `Team` and whose values give the total number of homeruns for each team. Sort the series from most home runs to least.

In [ ]:
team_home_runs = hitting.groupby("Team")["HR"].sum().sort_values(ascending=False)
team_home_runs.head()  # total home runs per team

## A live update for variance
For this problem, we will use the variance formula with delta degrees of freedom = 0,
\begin{equation}
    \text{variance} = \frac{1}{N} \sum_{j=1}^{N}(x_j - \bar{x})^2,
\end{equation}
which has the equivalent formulation (can you verify it?)
\begin{equation}
    \text{variance} = \frac{1}{N}\sum_{j=1}^N x_j^2 - \left(\frac{1}{N}\sum_{j=1}^N x_j\right)^2
\end{equation}
**PROMPT** Given the mean and variance of $N$ data points, $\bar{x}_N$, and $s^2_N$, design and implement an algorithm that will compute the variance of the dataset when it receives one additional data point. _Do not simply apply the variance formula to the updated dataset; for very large datasets, we may not want to recompute loads (a technical term) of numbers just to update with one single new number_. Test your function with the homerun totals for MLB teams. You can assume a new mystery team has a homerun total of 180 when testing your function.

First, some definitions to use:
$$ \bar X = N^{-1} \sum_{j = 1} ^ N X_j $$
$$ \bar X_N = N^{-1}[X_N + (N-1)\bar X_{N-1}] $$
$$ s^2_N = \frac{\sum_{j = 1} ^ N (X_j - \bar X_N)^2}{N - 1}
= \frac{\sum_{j = 1} ^ N (X_j - \bar X_{N - 1} + \bar X_{N - 1} - \bar X_N)^2}{N - 1} $$
$$ s^2_N = \frac{(N - 2)s^2_{N - 1} + (N - 1)(\bar X_{N - 1} - \bar X_N)^2
+ (X_N - \bar X_{N})^2}{N - 1} $$
$$ s_N^2={N-2\over N-1}s^2_{N-1}+{1\over N}(X_N-\bar X_{N-1})^2 $$

Equation 1 shows the definition for our sample mean $ \bar{X} $. Equation 2 is the incremental/iterative version of that same sample mean, after adding one new value. Equation 3 shows the beginning steps of defining the variance in terms of totals and sums, simplifying, some symbol manipulation, the summation goes to zero, and Equation 5 is the simplified result for calculating the incremental/iterative variance after adding a new data point. Let's also make some quick extra definitions:

We'll call our new data point $ a = 180 $.

In [ ]:
# now, let's put some things together
# the data we want to work with is team_home_runs data

team_home_runs_list = team_home_runs.to_list()

# given variables
N = len(team_home_runs_list)
Xbar_n = sum(team_home_runs_list) / len(team_home_runs_list)
Sn_2 = np.var(team_home_runs_list)

# make a new row for the new mystery team with a homerun total of 180
a = 180
team_name = "ABC"

# TODO make prettier
# old numbers to compare
print("old:")
print(f"{N=}")
print(f"{Xbar_n=}")
print(f"{Sn_2=}")

# compute updated N
N += 1  # we are adding 1 data point

# compute updated x bar
new_Xbar_n = N ** (-1) * (a + (N - 1) * Xbar_n)

# compute updated Sn_2
new_Sn_2 = (N - 2) / (N - 1) * (Sn_2) + (1) / (N) * (
    a - Xbar_n
) ** 2  # TODO Fix ZeroDivisionError

# TODO make prettier
# comparing new numbers
print("New:")
print(f"{N=}")
print(f"{new_Xbar_n=}")
print(f"{new_Sn_2=}")